id: I6560D38D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T03:00:13+00:00'
last_modified: '2022-06-09T04:42:44.392883+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3331
  title: པདྨ་བཀའ་ཐང་། ༼གསེར་བྲིས།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    BDAE:
      image_group_id: I3CN3566
      title: Volume 1 of pad+ma bka' thang / (gser bris/)
      total_pages: 494
      order: 1
      base_file: BDAE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
