id: P008130
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3331
  title: པདྨ་བཀའ་ཐང་། ༼གསེར་བྲིས།༽
  author: ''
  volumes:
    5e473a54cf7b477eacf9a2e13f8d311d:
      image_group_id: I3CN3566
      title: ''
      volume_number: 1
      total_pages: 494
ebook_metadata:
  title: པདྨ་བཀའ་ཐང་། ༼གསེར་བྲིས།༽
  author: ''
  sku: P008130
  cover: cover.jpg
  layers:
  - pagination
