id: P008130
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:03:35.263326
source_metadata:
  id: bdr:W3CN3331
  title: པདྨ་བཀའ་ཐང་། ༼གསེར་བྲིས།༽
  author: ''
  volumes:
    64a750aa9b764382bd0025d8b86d2dff:
      image_group_id: I3CN3566
      title: Volume 1 of pad+ma bka' thang / (gser bris/)
      volume_number: 1
      total_pages: 494
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
