id: opecha:P008130
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3331
  title: པདྨ་བཀའ་ཐང་། ༼གསེར་བྲིས།༽
  volume:
    64a750aa9b764382bd0025d8b86d2dff:
      image_group_id: I3CN3566
      title: Volume 1 of pad+ma bka' thang / (gser bris/)
      volume_number: 1
      total_pages: 494
  author: ''
ebook_metadata:
  title: པདྨ་བཀའ་ཐང་། ༼གསེར་བྲིས།༽
  author: ''
  sku: P008130
  cover: cover.jpg
  layers:
  - pagination
